name: release-please
on:
  push:
    branches:
      - main
  # Run daily to keep the release PR date current
  schedule:
    - cron: '1 0 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  common:
    uses: City-of-Helsinki/.github/.github/workflows/release-please.yml@main

  pypi-publish:
    needs: common
    if: ${{ needs.common.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -U setuptools wheel build
      - name: Build
        run: python -m build .
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
